class Giraffes(Mammals):
	def left_foot_forward(self):
		print("left food forward")
	def left_foot_back(self):
		print("left food back")
	def right_foot_forward(self):
		print("right food forward")
	def right_foot_back(self):
		print("right food back")
	def dance(self):
		self.left_foot_forward()
		self.left_foot_back()
		self.right_foot_back()
		self.right_foot_forward()

import turtle
>>> Q = turtle.Pen()

>>> Q.forward(100)
>>> Q.left(90)
>>> Q.forward(80)
>>> Q.right(90)
>>> Q.forward(50)
>>> W = turtle.Pen()
>>> W.forward(100)
>>> W.left(45)
>>> W.left(90)
>>> W.right(45)
>>> W.right(90)
>>> W.forward(10)
>>> W.forward(30)
>>> W.left(90)
>>> W.left(90)
>>> w.forward(10)
>>> W.forward(10)
>>> W.right(90)
>>> W.forward(45)
>>> W.right(90)
>>> W.forward(10)
>>> W.forward(5)
>>> e = turtle.Pen()
>>> e.forward(100)
>>> e.right(90)
>>> e.forward(50)
>>> e.forward(30)
>>> e.right(90)
>>> e.right(180)
>>> e.forward(50)
>>> r=turtle.Pen()
>>> r.forward(110)
>>> r.forward(10)
>>> r.forward(10)
>>> r.right(90)
>>> r.forward(30)
>>> r.forward(10)
>>> r.left(90)
>>> r.forward(10)
>>> r.forward(10)
>>> r.forward(20)
>>> W.forward(20)
>>> W.forward(10)
>>> e.forward(5)
>>> e.forward(5)
>>> W.forward(10)
>>> e.forward(5)
>>> e.forward(5)
>>> r.forward(5)
>>> r.forward(5)
>>> r.forward(5)
>>> Q.forward(15)